import { Quantico } from 'next/font/google';
import { Audiowide, Playwrite_AR_Guides, Bruno_Ace_SC } from 'next/font/google';
import './globals.css';

const quantico = Quantico({
  variable: '--font-quantico',
  weight: ['400', '700'],
  subsets: ['latin'],
});

const audiowide = Audiowide({
  variable: '--font-audiowide',
  weight: '400',
});

const playwriteAr = Playwrite_AR_Guides({
  variable: '--font-playwrite-ar',
  weight: '400',
});

const brunoAceSc = Bruno_Ace_SC({
  variable: '--font-bruno-ace-sc',
  weight: '400',
});

export const metadata = {
  title: 'iniAstratech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${quantico.variable} ${audiowide.variable} ${playwriteAr.variable} ${brunoAceSc.variable} h-full overflow-x-hidden antialiased bg-slate-950`}
      suppressHydrationWarning
    >
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col overflow-x-hidden bg-slate-950 text-white"
      >
        {children}
      </body>
    </html>
  );
}
